# Traefik static configuration
# Replace with your actual Traefik config as needed
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
certificatesResolvers:
  cloudflare:
    acme:
      email: your-email@example.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
api:
  dashboard: true
